# docker-compose.yml - 

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=gces_db
      - POSTGRES_USER=gces_user
      - POSTGRES_PASSWORD=gces_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gces_user -d gces_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://gces_user:gces_password@db:5432/gces_db
      - SECRET_KEY=minha-chave-secreta-de-desenvolvimento-pode-ser-qualquer-coisa
      - DEBUG=1
      - ON_SERVER=False  
      - SECURE_SSL_REDIRECT=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./www
      
    volumes:
      - ./www:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_HOST=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data: